[package]
name = "graphing_calc"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
rayon = "1.8"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true

[package.metadata.bundle]
name = "Graphing Calculator"
identifier = "com.twidilers.hihihioli.graping_calc"
#icon = ["icon.png"]
osx_minimum_system_version = "13.1"
